### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [keyboardDrummer/ParticleCompiler#116]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./modularLanguages/src/test/resources/AutoScalingMultiAZWithNotifications.yaml`

**line number(s):** [503]

**resource(s):** 

Missing egress rule means all traffic is allowed outbound.  Make this explicit if it is desired configuration

---

**severity:** warning

**filename:** `./modularLanguages/src/test/resources/AutoScalingMultiAZWithNotifications.yaml`

**line number(s):** [488]

**resource(s):** 

Elastic Load Balancer should have access logging enabled

---

**severity:** warning

**filename:** `./modularLanguages/src/test/resources/AutoScalingMultiAZWithNotifications.yaml`

**line number(s):** [503]

**resource(s):** 

Security group rules without a description obscure their purpose and may lead to bad practices in ensuring they only allow traffic from the ports and sources/destinations required.

---

**severity:** warning

**filename:** `./modularLanguages/src/test/resources/AutoScalingMultiAZWithNotifications.json`

**line number(s):** [430]

**resource(s):** 

Security group rules without a description obscure their purpose and may lead to bad practices in ensuring they only allow traffic from the ports and sources/destinations required.

---

**severity:** warning

**filename:** `./languageServer/src/test/resources/AutoScalingMultiAZWithNotifications.yaml`

**line number(s):** [488]

**resource(s):** 

Elastic Load Balancer should have access logging enabled

**Comment by keyboardDrummer** [comment]
I assume this issue has been filed automatically, given that security vulnerabilities in a CloudFormation template aren't relevant to this product. Dear requester, I applaud your enthusiasm for automation but please stop spamming me (and others).
