### ISSUE TITLE
'No main class detected' when executing "sbt run"

### ISSUE THREAD

**Issue by avidan-efody** [keyboardDrummer/ParticleCompiler#60]
88e9fe6d5b81:Miksilo$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

88e9fe6d5b81:Miksilo$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

88e9fe6d5b81:Miksilo $ sbt run
[info] Loading settings from assembly.sbt ...
[info] Loading project definition from /Users/miksilo/Miksilo/project
[info] Loading settings from build.sbt ...
[info] Set current project to miksilo (in build file:/Users/miksilo/Miksilo/)
[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1163)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1163)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / bgRun) No main class detected.
[error] Total time: 0 s, completed Sep 22, 2018 3:08:05 PM

88e9fe6d5b81:Miksilo $ uname -a
Darwin 88e9fe6d5b81.my-mac.my-company.com 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

**Comment by avidan-efody** [comment]
Should this be run from the playground/ directory, that has a src/main/scala directory?

```
88e9fe6d5b81:Miksilo avidane$ cd playground/
88e9fe6d5b81:playground avidane$ sbt run
[warn] No sbt.version set in project/build.properties, base directory: /Users/avidane/miksilo/Miksilo/playground
[info] Set current project to playground (in build file:/Users/avidane/miksilo/Miksilo/playground/)
[info] Updating ...
[info] Done updating.
[info] Compiling 50 Scala sources and 1 Java source to /Users/avidane/miksilo/Miksilo/playground/target/scala-2.12/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.6. Compiling...
[info]   Compilation completed in 14.439s.
[error] /Users/avidane/miksilo/Miksilo/playground/src/main/scala/application/Program.scala:10:12: object mxgraph is not a member of package com
[error] import com.mxgraph.swing.mxGraphComponent
[error]            ^
[error] /Users/avidane/miksilo/Miksilo/playground/src/main/scala/application/Program.scala:11:12: object oxbow is not a member of package org
[error] import org.oxbow.swingbits.dialog.task.TaskDialogs
```

**Comment by keyboardDrummer** [comment]
It should be `sbt playground/run` from the root directory. I'm afraid the docs got a bit outdated. I've updated them.
